project_id = "amkelczfwazutrciqtlk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
image_transformation = {enabled = true}

[auth]
enabled = true

[functions.asaas-create-payment]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-check-payment]
verify_jwt = true

[functions.affiliates-management]
verify_jwt = true

[functions.asaas-create-payment-with-split]
verify_jwt = true

[edge_runtime]
enabled = true

[analytics]
enabled = false
