-- Tarefa 3.1: Cria as tabelas administrativas ausentes ('notification_templates' e 'content_pages')

-- Tabela para templates de notificação
-- Usada para armazenar modelos de e-mail e outras notificações.
CREATE TABLE IF NOT EXISTS public.notification_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    subject text NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Tabela para páginas de conteúdo (CMS - Content Management System)
-- Usada para gerenciar páginas de conteúdo dinâmico no site.
CREATE TABLE IF NOT EXISTS public.content_pages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    title text NOT NULL,
    content jsonb,
    is_published boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Habilita RLS e define políticas de acesso para as novas tabelas
-- Apenas administradores poderão gerenciar os templates de notificação.
ALTER TABLE public.notification_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can manage notification templates" ON public.notification_templates;
CREATE POLICY "Admins can manage notification templates" ON public.notification_templates 
FOR ALL USING ((get_user_roles(auth.uid()) @> ARRAY['admin']));

-- Para o conteúdo, o público pode ler páginas publicadas, mas apenas admins podem gerenciar.
ALTER TABLE public.content_pages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read published content" ON public.content_pages;
CREATE POLICY "Public can read published content" ON public.content_pages 
FOR SELECT USING (is_published = true);

DROP POLICY IF EXISTS "Admins can manage content" ON public.content_pages;
CREATE POLICY "Admins can manage content" ON public.content_pages 
FOR ALL USING ((get_user_roles(auth.uid()) @> ARRAY['admin']));

-- Confirmação de que o script foi criado.
-- A execução real deve ser feita manualmente no painel do Supabase.